name: Run MEXC Pump/Dump Bot

on:
  schedule:
    - cron: '*/5 * * * *'
  workflow_dispatch:

jobs:
  run:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - uses: actions/setup-python@v4
      with:
        python-version: '3.11'
    - name: Install deps
      run: |
        pip install --upgrade pip
        pip install -r requirements.txt
    - name: Run bot
      env:
        BOT_TOKEN: ${{ secrets.BOT_TOKEN }}
        CHAT_ID:   ${{ secrets.CHAT_ID }}
      run: python bot.py
